configured_endpoints: 10
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/meorphis-test%2Fmeorphis-test-40-6fa81ed9f4660ce71f188152dd486f5238e567fb4876fd49bd93d4e540d78d5b.yml
