configured_endpoints: 1260
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/meorphis-test%2Fmeorphis-test-40-c2ffcecc38329cbf23fcdbb60f9f11a2b1e9ca589abd1599034a17cb81419847.yml
